import React, { useState, useEffect, useContext } from 'react';
import { useParams, Link } from 'react-router-dom';
import { 
    CheckCircle, XCircle, Clock, Info, ArrowLeft, 
    FileText, MapPin, Globe, AlertTriangle, Lightbulb,
    ChevronRight, Shield, Download, ExternalLink, Sparkles
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import AuthContext from '../context/AuthContext';
import api from '../services/api';

const ApplicationGuidePage = () => {
    const { id } = useParams();
    const { user } = useContext(AuthContext);
    const [scheme, setScheme] = useState(null);
    const [guide, setGuide] = useState(null);
    const [loading, setLoading] = useState(true);
    const [activeStep, setActiveStep] = useState(0);

    useEffect(() => {
        const fetchGuideData = async () => {
            try {
                // Fetch Scheme Details
                const schemeRes = await api.get(`/schemes/${id}`);
                setScheme(schemeRes.data);

                // Fetch AI-powered Guide
                const guideRes = await api.get(`/schemes/${id}/guide`);
                setGuide(guideRes.data);
            } catch (error) {
                console.error("Failed to fetch guide", error);
            } finally {
                setLoading(false);
            }
        };

        if (id) fetchGuideData();
    }, [id]);

    if (loading) return <div className="min-h-screen bg-[#020617] flex items-center justify-center text-primary font-black animate-pulse">GENERATING PATHWAY...</div>;
    if (!scheme || !guide) return <div className="min-h-screen bg-[#020617] flex items-center justify-center text-white">Scheme Not Found</div>;

    return (
        <div className="min-h-screen bg-[#020617] py-20 px-4 sm:px-6 lg:px-8">
            <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="max-w-7xl mx-auto space-y-12"
            >
                {/* Top Nav */}
                <div className="flex items-center justify-between">
                    <Link to="/schemes" className="flex items-center gap-2 text-slate-400 hover:text-white transition-all font-bold">
                        <ArrowLeft className="w-5 h-5" /> Back to Schemes
                    </Link>
                    <div className="flex items-center gap-2 bg-emerald-500/10 text-emerald-400 px-4 py-2 rounded-full border border-emerald-500/20 text-xs font-black uppercase tracking-widest">
                        <Shield className="w-4 h-4" /> Personalized Guide
                    </div>
                </div>

                {/* Header Section */}
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-end">
                    <div className="lg:col-span-8">
                        <h1 className="text-4xl lg:text-6xl font-black text-white tracking-tighter leading-none mb-6">
                            {scheme.name} <br/> <span className="text-primary italic">Application Pathway.</span>
                        </h1>
                        <p className="text-slate-400 text-lg font-medium leading-relaxed max-w-2xl">
                            Follow this structured guide generated by SmartGov AI to maximize your application success probability.
                        </p>
                    </div>
                    <div className="lg:col-span-4 bg-white/5 p-8 rounded-[2.5rem] border border-white/10 flex flex-col justify-center items-center text-center purple-glow">
                        <div className="p-4 bg-emerald-500/20 rounded-full mb-4">
                            <CheckCircle className="w-10 h-10 text-emerald-400" />
                        </div>
                        <span className="text-[10px] text-emerald-400/60 font-black uppercase tracking-widest block mb-1">Status Resonance</span>
                        <h2 className="text-2xl font-black text-emerald-400">{guide.eligibilityStatus.toUpperCase()}</h2>
                    </div>
                </div>

                {/* Main Content Grid */}
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">
                    
                    {/* Left Column: Timeline & Steps */}
                    <div className="lg:col-span-7 space-y-10">
                        <div className="glassmorphism p-10 rounded-[2.5rem] border-white/10">
                            <h3 className="text-2xl font-black text-white mb-8 flex items-center gap-3">
                                <Clock className="text-primary w-6 h-6" /> Execution Timeline
                            </h3>
                            <div className="space-y-4">
                                {guide.applicationSteps.map((step, idx) => (
                                    <motion.div 
                                        key={idx}
                                        className={`flex gap-6 p-6 rounded-3xl transition-all border ${
                                            activeStep === idx 
                                            ? 'bg-primary/10 border-primary shadow-xl shadow-primary/10' 
                                            : 'bg-white/5 border-white/5 opacity-60'
                                        }`}
                                        onClick={() => setActiveStep(idx)}
                                        whileHover={{ x: 5 }}
                                    >
                                        <div className={`w-10 h-10 rounded-xl flex items-center justify-center font-black ${
                                            activeStep === idx ? 'bg-primary text-white' : 'bg-slate-800 text-slate-500'
                                        }`}>
                                            {idx + 1}
                                        </div>
                                        <div className="flex-1">
                                            <p className="text-white font-bold leading-relaxed">{step}</p>
                                            {activeStep === idx && (
                                                <div className="mt-4 flex gap-4">
                                                    <button className="text-[10px] font-black uppercase tracking-widest text-primary hover:text-white transition-all flex items-center gap-1">
                                                       <CheckCircle className="w-3 h-3" /> Mark as Complete
                                                    </button>
                                                </div>
                                            )}
                                        </div>
                                    </motion.div>
                                ))}
                            </div>
                            <div className="mt-10 pt-10 border-t border-white/5 flex justify-between items-center text-slate-500">
                                <span className="text-sm font-bold">Estimated Time: {scheme.avgProcessingTime}</span>
                                <div className="flex -space-x-2">
                                    {[1,2,3].map(i => <div key={i} className="w-8 h-8 rounded-full border-2 border-[#020617] bg-slate-800" />)}
                                </div>
                            </div>
                        </div>

                        {/* Submission Hub */}
                        <div className="glassmorphism p-10 rounded-[2.5rem] border-white/10 purple-glow bg-gradient-to-br from-indigo-500/5 to-purple-500/5">
                            <h3 className="text-2xl font-black text-white mb-8 flex items-center gap-3">
                                <ExternalLink className="text-secondary w-6 h-6" /> Submission Hub
                            </h3>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                <div className="space-y-3">
                                    <span className="text-[10px] font-black uppercase tracking-widest text-slate-500">Digital Gateway</span>
                                    <h4 className="text-white font-black text-xl flex items-center gap-2">
                                        <Globe className="w-5 h-5 text-blue-400" /> Web Portal
                                    </h4>
                                    <p className="text-slate-400 text-sm font-medium">Apply via the official government portal secured with BharatSign.</p>
                                    <a href={guide.submissionDetails.website} className="bg-white text-slate-900 px-6 py-3 rounded-xl font-bold text-sm inline-block mt-2 hover:scale-105 transition-all">Official Portal <ChevronRight className="w-4 h-4 inline" /></a>
                                </div>
                                <div className="space-y-3">
                                    <span className="text-[10px] font-black uppercase tracking-widest text-slate-500">Physical Gateway</span>
                                    <h4 className="text-white font-black text-xl flex items-center gap-2">
                                        <MapPin className="w-5 h-5 text-red-400" /> Local Office
                                    </h4>
                                    <p className="text-slate-400 text-sm font-medium">{guide.submissionDetails.officeAddress}</p>
                                    <button className="text-sm font-bold text-primary hover:text-white underline underline-offset-4 decoration-primary/30 mt-2 block">Find Nearest Common Service Centre (CSC)</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Right Column: Checklist & Tips */}
                    <div className="lg:col-span-5 space-y-10">
                        {/* Status Card */}
                        <div className="glassmorphism p-10 rounded-[2.5rem] border-white/10">
                            <h3 className="text-2xl font-black text-white mb-2 tracking-tight">Requirement Checklist</h3>
                            <p className="text-slate-500 text-sm font-medium mb-8 uppercase tracking-widest">Document Integrity Scan</p>
                            
                            <div className="space-y-4">
                                {guide.requiredDocuments.map((doc, idx) => (
                                    <div key={idx} className="flex justify-between items-center bg-white/5 p-5 rounded-2xl border border-white/5 group hover:border-white/10 transition-all">
                                        <div className="flex items-center gap-4">
                                            <div className={`w-3 h-3 rounded-full ${doc.status === 'uploaded' ? 'bg-emerald-500' : 'bg-red-500'} shadow-lg`} />
                                            <span className="text-slate-200 font-bold">{doc.name}</span>
                                        </div>
                                        {doc.status === 'uploaded' ? (
                                            <CheckCircle className="text-emerald-500 w-5 h-5 opacity-60" />
                                        ) : (
                                            <Link to="/vault" className="text-xs font-black uppercase tracking-widest text-primary hover:text-white transition-all bg-primary/10 px-4 py-2 rounded-lg border border-primary/20">
                                                Upload Now
                                            </Link>
                                        )}
                                    </div>
                                ))}
                            </div>

                            <button className="w-full mt-10 p-6 bg-slate-900/50 rounded-3xl border border-white/5 hover:border-primary/30 transition-all flex items-center justify-between group">
                                <div className="flex items-center gap-4 text-left">
                                    <Download className="w-6 h-6 text-slate-500 group-hover:text-primary transition-colors" />
                                    <div>
                                        <span className="block text-white font-bold">Download Guidance PDF</span>
                                        <span className="text-[10px] text-slate-600 font-black uppercase tracking-widest">Offline reference manual</span>
                                    </div>
                                </div>
                                <ChevronRight className="w-5 h-5 text-slate-700" />
                            </button>
                        </div>

                        {/* AI Insights & Mistakes */}
                        <div className="space-y-8">
                            <div className="p-10 bg-gradient-to-br from-amber-500/10 to-orange-500/10 rounded-[2.5rem] border border-amber-500/20">
                                <h3 className="text-amber-500 font-black flex items-center gap-2 mb-6 uppercase tracking-widest text-sm">
                                    <AlertTriangle className="w-5 h-5" /> Critical Pitfalls
                                </h3>
                                <ul className="space-y-4">
                                    {guide.commonMistakes.map((mistake, i) => (
                                        <li key={i} className="flex gap-3 text-slate-300 font-medium text-sm leading-relaxed">
                                            <div className="w-1.5 h-1.5 rounded-full bg-amber-500/50 mt-2 flex-shrink-0" />
                                            {mistake}
                                        </li>
                                    ))}
                                </ul>
                            </div>

                            <div className="p-10 bg-gradient-to-br from-indigo-500/10 to-blue-500/10 rounded-[2.5rem] border border-indigo-500/20">
                                <h3 className="text-indigo-400 font-black flex items-center gap-2 mb-6 uppercase tracking-widest text-sm">
                                    <Lightbulb className="w-5 h-5" /> SmartGov Strategy
                                </h3>
                                <ul className="space-y-4">
                                    {guide.tips.map((tip, i) => (
                                        <li key={i} className="flex gap-3 text-slate-300 font-medium text-sm leading-relaxed">
                                            <Sparkles className="w-4 h-4 text-indigo-400 flex-shrink-0 mt-1" />
                                            {tip}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        </div>

                        <button className="w-full py-6 bg-primary text-white rounded-[2.0rem] font-black text-xl shadow-2xl shadow-primary/30 hover:scale-[1.02] active:scale-95 transition-all flex items-center justify-center gap-4 group">
                             Initialize Live Submission
                             <ChevronRight className="w-6 h-6 group-hover:translate-x-2 transition-transform" />
                        </button>
                    </div>
                </div>
            </motion.div>
        </div>
    );
};

export default ApplicationGuidePage;
